sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: nightly

before_install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

install:
  - composer self-update
  - composer install

script:
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,vendor/,web/app/plugins,web/app/mu-plugins -n -s .
