---

# Ensure symlinks source exists befor deleting target
- name: ROKKET | Export local wordpress database
  local_action: "command wp db export /tmp/wpcli_database.sql chdir={{rokket_local_project_root}}"

- name: ROKKET | Sync exported database to remote server
  synchronize: src=/tmp/wpcli_database.sql dest=/tmp/wpcli_database.sql

- name: ROKKET | Import database to remote
  command: "{{ansistrano_deploy_to}}/shared/wp-cli.phar db import /tmp/wpcli_database.sql --debug chdir={{rokket_remote_project_root}}"

- name: ROKKET | Replace old domain with new
  command: "{{ansistrano_deploy_to}}/shared/wp-cli.phar search-replace {{rokket_local_url}} {{rokket_remote_url}} --skip-columns=guid --url={{rokket_local_url}} --debug chdir={{rokket_remote_project_root}}"
