---

# Ensure symlinks source exists befor deleting target
- name: ROKKET | Export remote wordpress database
  command: "{{ansistrano_deploy_to}}/shared/wp-cli.phar db export /tmp/wpcli_database.sql chdir={{rokket_remote_project_root}}"

- name: ROKKET | Sync exported database to local machine
  local_action: synchronize src=/tmp/wpcli_database.sql dest=/tmp/wpcli_database.sql

- name: ROKKET | Import database to local
  local_action: "command wp db import /tmp/wpcli_database.sql --debug chdir={{rokket_local_project_root}}"

- name: ROKKET | Replace old domain with new
  local_action: "command wp search-replace {{rokket_remote_url}} {{rokket_local_url}} --skip-columns=guid --url={{rokket_remote_url}} --debug chdir={{rokket_local_project_root}}"
